#!/bin/sh
samba-tool domain provision --server-role=dc --use-rfc2307 \
--dns-backend=SAMBA_INTERNAL --realm=AD.$CNAME.BLA \
--domain=$CNAME --adminpass=XXXXXXXX \
--option="disable netbios = yes" \
--option="dns forwarder = 10.x.x.1" \
--option="allow dns updates = nonsecure"
