#!/bin/sh
BASEDIR=/dozer/data/samba
find $BASEDIR/homes/*/.recycler $BASEDIR/public/.recycler -type f \( -name 'Copy #*' -o -name '*.tmp' -o -name '~$*' -o -ctime +2 \) -delete
find $BASEDIR/homes/*/.recycler $BASEDIR/public/.recycler \! -name .recycler -empty -delete
