#!/bin/sh
# dhclient change hostname script for Ubuntu
# /etc/dhcp/dhclient-exit-hooks.d/sethostname
# logs in /var/log/upstart/network-interface-eth0.log

# for debugging:
#echo "set domain BEGIN"
#export
#set -x

if [ $reason = "BOUND" ]; then
    echo new_ip_address=$new_ip_address
    echo new_domain_name=$new_domain_name

    host_name=$(hostname -s)
    olddomain=$(hostname -d)
    if [ "$olddomain" != "$new_domain_name" ]; then

        # Update /etc/hosts if needed
        TMPHOSTS=/etc/hosts.dhcp.new
        if ! grep "$new_ip_address $host_name.$new_domain_name $host_name" /etc/hosts; then
            # Remove the 127.0.1.1 put there by the debian installer
            grep -v '127\.0\.1\.1 ' < /etc/hosts > $TMPHOSTS
            # Add the our new ip address and name
            echo "$new_ip_address $host_name.$new_domain_name $host_name" >> $TMPHOSTS
            mv $TMPHOSTS /etc/hosts
        fi

        # Recreate SSH2 keys
        # why?
#        export DEBIAN_FRONTEND=noninteractive 
#        dpkg-reconfigure openssh-server
    fi
fi
#echo "set domain END"