#!/bin/bash

apt-get update
apt-get install -y lsb-release # optional
CODENAME=`lsb_release -c -s`
wget -O- http://rspamd.com/apt-stable/gpg.key | apt-key add -
echo "deb http://rspamd.com/apt-stable/ $CODENAME main" > /etc/apt/sources.list.d/rspamd.list
echo "deb-src http://rspamd.com/apt-stable/ $CODENAME main" >> /etc/apt/sources.list.d/rspamd.list
#apt-get update
#apt-get install rspamd